# Global settings applied to the whole site
[build]
  base = "radio_referbish_FE
  publish = "dist/browser"
  command = "npm run build:prod"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
