# Global settings applied to the whole site
[build]
  publish = "dist/radio_referbish_FE"
  command = "npm run build:prod"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

